# Generated by Django 5.0.6 on 2024-07-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='taskanswer',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файлы ответа'),
        ),
    ]
